export const defaultData = [
  {
    name: 'Lucca Geraldo Gael Cavalcanti',
    birthdate: '27/05/1970',
    sex: 'M',
    height: '1,67',
    weight: '106',
    nationality: 'Brasileiro',
    email: 'lucca_geraldo_cavalcanti@lynce.com.br',
    cel: '(19) 3864-8448',
  },
  {
    name: 'Lucca Geraldo Gael Cavalcanti',
    birthdate: '27/05/1970',
    sex: 'M',
    height: '1,67',
    weight: '106',
    nationality: 'Brasileiro',
    email: 'lucca_geraldo_cavalcanti@lynce.com.br',
    cel: '(19) 3864-8448',
  },
  {
    name: 'Lucca Geraldo Gael Cavalcanti',
    birthdate: '27/05/1970',
    sex: 'M',
    height: '1,67',
    weight: '106',
    nationality: 'Brasileiro',
    email: 'lucca_geraldo_cavalcanti@lynce.com.br',
    cel: '(19) 3864-8448',
  },
  {
    name: 'Lucca Geraldo Gael Cavalcanti',
    birthdate: '27/05/1970',
    sex: 'M',
    height: '1,67',
    weight: '106',
    nationality: 'Brasileiro',
    email: 'lucca_geraldo_cavalcanti@lynce.com.br',
    cel: '(19) 3864-8448',
  },
];
